# Generated by Django 5.2.17 on 2026-09-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_entity_fixed_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='document',
            name='recurrence_months',
        ),
    ]
