# Generated by Django 5.2.17 on 2026-09-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_is_recurring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=43, unique=True, verbose_name='الرمز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='المستند')),
            ],
            options={
                'verbose_name': 'رابط مشاركة',
                'verbose_name_plural': 'روابط المشاركة',
                'ordering': ['-created_at'],
            },
        ),
    ]
