# Generated by Django 5.2.17 on 2026-09-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reminder_days',
            field=models.CharField(blank=True, help_text='أيام قبل الانتهاء مفصولة بفواصل. الحقل الفارغ يعني استخدام الإعداد الافتراضي.', max_length=60, verbose_name='أيام التنبيه'),
        ),
        migrations.AddField(
            model_name='document',
            name='snoozed_until',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='الملف')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('reason', models.CharField(choices=[('renewed', 'تجديد'), ('replaced', 'استبدال الملف'), ('restored', 'استرجاع نسخة قديمة')], max_length=10, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='المستند')),
            ],
            options={
                'verbose_name': 'نسخة سابقة',
                'verbose_name_plural': 'النسخ السابقة',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
